export const divisionsAndDistricts = {
  dhaka: {
    name: "Dhaka",
    districts: {
      dhaka: {
        name: "Dhaka",
        thanas: {
          dhaka_sadar: {
            name: "Dhaka Sadar",
            locations: [
              "300 Feet / Purbachal",
              "Adabor",
              "Aftabnagar",
              "Agargaon",
              "Airport Area",
              "Arambagh",
              "Asad Gate",
              "Ashkona",
              "Azimpur",
              "Badda (Merul)",
              "Badda (Middle)",
              "Badda (South)",
              "Bailey Road",
              "Banani",
              "Banani DOHS",
              "Banasree",
              "Bangshal",
              "Baridhara",
              "Baridhara DOHS",
              "Basabo",
              "Bashundhara R/A",
              "Bhashantek",
              "Bijoy Sarani",
              "Bongshal",
              "Bosila (Mohammadpur)",
              "BUET Area",
              "Cantonment",
              "Central Road",
              "Chankharpul",
              "Chawkbazar",
              "Dakshinkhan",
              "Darus Salam",
              "Demra",
              "Dhanmondi",
              "Dhanmondi R/A",
              "Dilkusha",
              "Dilu Road",
              "DOHS (Baridhara)",
              "DOHS (Mirpur)",
              "DOHS (Mohakhali)",
              "Donia",
              "DU Campus (Dhaka University)",
              "Elephant Road",
              "Eskaton",
              "Fakirapool",
              "Farmgate",
              "Gabtoli",
              "Gandaria",
              "Gopibagh",
              "Goran",
              "Green Road",
              "Gulistan",
              "Gulshan 1",
              "Gulshan 2",
              "Hatirjheel Area",
              "Hatirpool",
              "Hazaribagh",
              "Hemayetpur",
              "Ibrahimpur",
              "Indira Road",
              "Islampur",
              "Japan Garden City",
              "Jatrabari",
              "Jigatola",
              "Jurain",
              "Kachukhet",
              "Kafrul",
              "Kakrail",
              "Kalabagan",
              "Kalachandpur",
              "Kallyanpur",
              "Kalshi",
              "Kamrangirchar",
              "Kathalbagan",
              "Kawran Bazar",
              "Kazipara",
              "Keraniganj",
              "Khilgaon",
              "Khilkhet",
              "Kotwali",
              "Kuril / Kuril Bishwa Road",
              "Lalbagh",
              "Lalmatia",
              "Maghbazar",
              "Malibagh",
              "Malibagh Chowdhury Para",
              "Manikdi",
              "Maniknagar",
              "Matikata",
              "Meradia",
              "Mirpur 1",
              "Mirpur 10",
              "Mirpur 11",
              "Mirpur 12",
              "Mirpur 13",
              "Mirpur 14",
              "Mirpur 2",
              "Mirpur 6",
              "Mirpur 7",
              "Mirpur DOHS",
              "Moghbazar (Wireless)",
              "Mohakhali",
              "Mohakhali DOHS",
              "Mohammadpur",
              "Mohammadpur Housing",
              "Monipuripara",
              "Motijheel",
              "Mugda",
              "Nakhalpara",
              "Narinda",
              "Nadda",
              "Nawabganj",
              "New Eskaton",
              "New Market",
              "Niketon",
              "Nikunja 1",
              "Nikunja 2",
              "Nilkhet",
              "Paikpara",
              "Pallabi",
              "Paltan",
              "Panthapath",
              "Paribagh",
              "PC Culture Housing",
              "Peelkhana",
              "Postogola",
              "Purana Paltan",
              "Raja Bazar (East/West)",
              "Rajarbagh",
              "Ramna",
              "Rampura",
              "Rampura Banasree",
              "Rayer Bazar",
              "Rayerbag",
              "Rupnagar",
              "Sabujbagh",
              "Sadarghat",
              "Saidabad (Sayedabad)",
              "Science Lab",
              "Segunbagicha",
              "Shahbagh",
              "Shahjahanpur",
              "Shanir Akhra",
              "Shantinagar",
              "Shekhertek",
              "Sher-e-Bangla Nagar",
              "Shewrapara",
              "Shiddheswari",
              "Shukrabad",
              "Shyamoli",
              "Siddheswari",
              "Sutrapur",
              "Taltola (Agargaon/Khilgaon)",
              "Tejgaon",
              "Tejgaon Industrial Area",
              "Tejkunipara",
              "Tikatuli",
              "Uttara",
              "Uttara Sector 1-14",
              "Uttarkhan",
              "Vatara",
              "Wari",
              "Zigatola",
            ],
          },
          gulshan: {
            name: "Gulshan",
            locations: ["Gulshan 1", "Gulshan 2", "Baridhara", "Banani"],
          },
          mirpur: {
            name: "Mirpur",
            locations: [
              "Mirpur 1",
              "Mirpur 2",
              "Mirpur 10",
              "Mirpur 11",
              "Mirpur 12",
            ],
          },
          uttara: {
            name: "Uttara",
            locations: [
              "Uttara 1",
              "Uttara 2",
              "Uttara 3",
              "Uttara 4",
              "Uttara 5",
              "Uttara 6",
            ],
          },
          mohakhali: {
            name: "Mohakhali",
            locations: ["Basundhara", "Kawran Bazar", "Badda", "Rampura"],
          },
          badda: {
            name: "Badda",
            locations: ["Badda", "Banani", "Gulshan", "Bashundhara"],
          },
          savar: {
            name: "Savar",
            locations: ["Savar Sadar", "Ashulia", "Dhakasuara", "Pubail"],
          },
          narayanganj: {
            name: "Narayanganj",
            locations: ["Sadar", "Fatulla", "Siddhirganj", "Araihazar"],
          },
        },
      },
      narayanganj: {
        name: "Narayanganj",
        thanas: {
          narayanganj_sadar: {
            name: "Narayanganj Sadar",
            locations: ["Narayanganj", "Bidyapati", "Belpul"],
          },
          siddorganj: {
            name: "Siddorganj",
            locations: ["Siddorganj", "Dhalpur"],
          },
          araihazar: {
            name: "Araihazar",
            locations: ["Araihazar", "Haripur", "Keshabpur"],
          },
          shyampur: { name: "Shyampur", locations: ["Shyampur", "Chandra"] },
        },
      },
      gazipur: {
        name: "Gazipur",
        thanas: {
          gazipur_sadar: {
            name: "Gazipur Sadar",
            locations: ["Gazipur", "Champ", "Tongi"],
          },
          kaliakoir: {
            name: "Kaliakoir",
            locations: ["Kaliakoir", "Dakshin Gaon"],
          },
          tongi: { name: "Tongi", locations: ["Tongi", "Brahmonbaria"] },
          sreepur: { name: "Sreepur", locations: ["Sreepur", "Dharol"] },
        },
      },
      tangail: {
        name: "Tangail",
        thanas: {
          tangail_sadar: {
            name: "Tangail Sadar",
            locations: ["Tangail", "Modhupur"],
          },
          kalihati: { name: "Kalihati", locations: ["Kalihati", "Nagarpur"] },
          nagarpur: { name: "Nagarpur", locations: ["Nagarpur", "Trishal"] },
          basail: { name: "Basail", locations: ["Basail", "Bashail"] },
        },
      },
      kishoreganj: {
        name: "Kishoreganj",
        thanas: {
          kishoreganj_sadar: {
            name: "Kishoreganj Sadar",
            locations: ["Kishoreganj", "Bhaishangar"],
          },
          katihar: { name: "Katihar", locations: ["Katihar", "Tiwail"] },
          bhairab: { name: "Bhairab", locations: ["Bhairab", "Pakundia"] },
          itna: { name: "Itna", locations: ["Itna", "Karimpur"] },
        },
      },
      manikganj: {
        name: "Manikganj",
        thanas: {
          manikganj_sadar: {
            name: "Manikganj Sadar",
            locations: ["Manikganj", "Dautipur"],
          },
          ghior: { name: "Ghior", locations: ["Ghior", "Jamuna Par"] },
          haripur: { name: "Haripur", locations: ["Haripur", "Sutia"] },
          saturia: { name: "Saturia", locations: ["Saturia", "Brahmin Bazar"] },
        },
      },
      munshiganj: {
        name: "Munshiganj",
        thanas: {
          munshiganj_sadar: {
            name: "Munshiganj Sadar",
            locations: ["Munshiganj", "Baliakandi"],
          },
          louhajanj: { name: "Louhajanj", locations: ["Louhajanj", "Tunggi"] },
          sreenagar: { name: "Sreenagar", locations: ["Sreenagar", "Gazaria"] },
          sirajdikhan: {
            name: "Sirajdikhan",
            locations: ["Sirajdikhan", "Narsingdi"],
          },
        },
      },
      shariatpur: {
        name: "Shariatpur",
        thanas: {
          shariatpur_sadar: {
            name: "Shariatpur Sadar",
            locations: ["Shariatpur", "Naria"],
          },
          naria: { name: "Naria", locations: ["Naria", "Zanjira"] },
          zanjira: { name: "Zanjira", locations: ["Zanjira", "Bhedarganj"] },
          bhedarganj: {
            name: "Bhedarganj",
            locations: ["Bhedarganj", "Raiganj"],
          },
        },
      },
      rajbari: {
        name: "Rajbari",
        thanas: {
          rajbari_sadar: {
            name: "Rajbari Sadar",
            locations: ["Rajbari", "Bagha"],
          },
          baliakandi: {
            name: "Baliakandi",
            locations: ["Baliakandi", "Sreenagar"],
          },
          kalukhali: {
            name: "Kalukhali",
            locations: ["Kalukhali", "Bikripur"],
          },
          goalanda: { name: "Goalanda", locations: ["Goalanda", "Chandpur"] },
        },
      },
      madaripur: {
        name: "Madaripur",
        thanas: {
          madaripur_sadar: {
            name: "Madaripur Sadar",
            locations: ["Madaripur", "Shibchar"],
          },
          rajoir: { name: "Rajoir", locations: ["Rajoir", "Satakandi"] },
          shibchar: { name: "Shibchar", locations: ["Shibchar", "Raipur"] },
          kalkini: { name: "Kalkini", locations: ["Kalkini", "Dhulia"] },
        },
      },
    },
  },
  rajshahi: {
    name: "Rajshahi",
    districts: {
      rajshahi: {
        name: "Rajshahi",
        thanas: {
          rajshahi_sadar: {
            name: "Rajshahi Sadar",
            locations: [
              "Aam Chattar (Amchattar)",
              "Alupatty",
              "Baharampur",
              "Balia Pukur",
              "Bangabari",
              "Bank Colony",
              "Beldarpara",
              "Bhadra",
              "Bhadra More",
              "Bheripara",
              "Binodpur",
              "Binodpur Bazar",
              "Boalia",
              "Bornali More",
              "Bospara",
              "BSCIC Industrial Area",
              "Budhpara",
              "C&B More",
              "Cantonment Area",
              "Chandrima R/A",
              "Choto Bongram",
              "Court Station",
              "Dargapara",
              "Dashmari",
              "Dingadoba",
              "Fudkipara",
              "Ghoramara",
              "Greater Road",
              "Harian",
              "Hatem Khan",
              "Hetemkhan",
              "Horagram",
              "Housing Estate",
              "Kadirganj",
              "Kajla (Kazla)",
              "Kajla Gate",
              "Kalabagan",
              "Kashiadanga",
              "Katakhali",
              "Kazihata",
              "Kharkhari",
              "Kumarpara",
              "Laxmipur (Lokkhipur)",
              "Laxmipur More",
              "Malopara",
              "Meherchandi",
              "Mission Hospital Area",
              "Mohish Bathan",
              "Monnafer Mor",
              "Motihar",
              "Mundumala",
              "Munshidanga",
              "Nawdapara",
              "New Market",
              "Padma Residential Area",
              "Pathan Para",
              "Police Line",
              "Rail Gate",
              "Rail Station Area",
              "Rajshahi College Area",
              "Rajshahi Court",
              "Rajshahi Medical College Area",
              "Rajshahi University Area (RU)",
              "Rani Bazar",
              "Raninagar",
              "Raypara",
              "Reshom Potty",
              "RUET Campus",
              "Sagarpara",
              "Saheb Bazar (Shaheb Bazar)",
              "Shalbagan",
              "Sheikh Para",
              "Shiroil",
              "Shiroil Colony",
              "Sopura",
              "Station Road",
              "Talaimari",
              "Terokhadia",
              "Tikapara",
              "Uposhahar",
              "Uposhahar Sector 1",
              "Uposhahar Sector 2",
              "Uposhahar Sector 3",
              "Uposhahar Sector 4",
              "Vatapara",
              "Vodra (Bhadra)",
              "Zero Point",
            ],
          },
          boalia: { name: "Boalia", locations: ["Boalia", "Peelkhana"] },
          motihar: { name: "Motihar", locations: ["Motihar", "Ramnagar"] },
          paba: { name: "Paba", locations: ["Paba", "Ashraful Nagar"] },
          tanore: { name: "Tanore", locations: ["Tanore", "Nazipur"] },
        },
      },
      natore: {
        name: "Natore",
        thanas: {
          natore_sadar: {
            name: "Natore Sadar",
            locations: ["Natore", "Singra"],
          },
          singhabad: { name: "Singhabad", locations: ["Singhabad", "Goshail"] },
          baraigram: {
            name: "Baraigram",
            locations: ["Baraigram", "Gopalpur"],
          },
          gurudaspur: {
            name: "Gurudaspur",
            locations: ["Gurudaspur", "Belkandi"],
          },
        },
      },
      naogaon: {
        name: "Naogaon",
        thanas: {
          naogaon_sadar: {
            name: "Naogaon Sadar",
            locations: ["Naogaon", "Atabari"],
          },
          raninagar: {
            name: "Raninagar",
            locations: ["Raninagar", "Kaligarh"],
          },
          patnitala: {
            name: "Patnitala",
            locations: ["Patnitala", "Parbatipur"],
          },
          badalgachhi: {
            name: "Badalgachhi",
            locations: ["Badalgachhi", "Sorjppur"],
          },
        },
      },
      chapainawabganj: {
        name: "Chapainawabganj",
        thanas: {
          chapainawabganj_sadar: {
            name: "Chapainawabganj Sadar",
            locations: ["Chapainawabganj", "Islampur"],
          },
          shibganj: { name: "Shibganj", locations: ["Shibganj", "Goalpokhor"] },
          nachole: { name: "Nachole", locations: ["Nachole", "Bhimpur"] },
          gomostapur: {
            name: "Gomostapur",
            locations: ["Gomostapur", "Dakshin Dinajpur"],
          },
        },
      },
      bogura: {
        name: "Bogura",
        thanas: {
          bogura_sadar: {
            name: "Bogura Sadar",
            locations: ["Bogura", "Satmatha", "Kahaloo"],
          },
          sherpur: { name: "Sherpur", locations: ["Sherpur", "Sukhanpur"] },
          sonatola: { name: "Sonatola", locations: ["Sonatola", "Bamongram"] },
          kahaloo: { name: "Kahaloo", locations: ["Kahaloo", "Dhupchanchia"] },
          sariakandi: {
            name: "Sariakandi",
            locations: ["Sariakandi", "Doyapur"],
          },
        },
      },
      sirajganj: {
        name: "Sirajganj",
        thanas: {
          sirajganj_sadar: {
            name: "Sirajganj Sadar",
            locations: ["Sirajganj", "Bashundhara"],
          },
          tarash: { name: "Tarash", locations: ["Tarash", "Porshuram"] },
          chauhali: { name: "Chauhali", locations: ["Chauhali", "Hridoypur"] },
          royppur: { name: "Royppur", locations: ["Royppur", "Mitapukur"] },
          belkuchi: { name: "Belkuchi", locations: ["Belkuchi", "Salchipur"] },
        },
      },
      pabna: {
        name: "Pabna",
        thanas: {
          pabna_sadar: { name: "Pabna Sadar", locations: ["Pabna", "Banani"] },
          faridpur: { name: "Faridpur", locations: ["Faridpur", "Chandpur"] },
          bhangura: { name: "Bhangura", locations: ["Bhangura", "Atgharh"] },
          sujanagar: {
            name: "Sujanagar",
            locations: ["Sujanagar", "Chatushkone"],
          },
          ishwardi: { name: "Ishwardi", locations: ["Ishwardi", "Kalupur"] },
        },
      },
    },
  },
  khulna: {
    name: "Khulna",
    districts: {
      khulna: {
        name: "Khulna",
        thanas: {
          khulna_sadar: {
            name: "Khulna Sadar",
            locations: [
              "250 Bed Hospital Area",
              "7 No. Ghat",
              "Ahsan Ahmed Road",
              "Alam Nagar",
              "Alutala",
              "Amtala",
              "Arabpur",
              "Arongghata",
              "Azam Khan Commerce College Area",
              "B.K. Roy Road",
              "Baiti Para",
              "Banorgati (Banar Gati)",
              "Bania Khamar",
              "Basupara (Bosu Para)",
              "Baten Road",
              "Bastuhara",
              "Bhashani Nagar",
              "Bikrampur",
              "Binoy Para",
              "Boro Bazar",
              "Boro Boyra",
              "Boyra (Main Road)",
              "Boyra Bazar",
              "Boyra College Road",
              "BL College Area (Daulatpur)",
              "BSCIC Industrial Area",
              "C&B Colony",
              "Cantonment Area",
              "Choto Boyra",
              "Choto Mirzapur",
              "Christian Colony",
              "Circuit House Area",
              "City College Area",
              "Customs Ghat",
              "Dakbangla More",
              "Darul Ulum Madrasa Area",
              "Daulatpur",
              "Daulatpur Bazar",
              "Deyana",
              "Dighir Par",
              "Dolkhola",
              "Farazipara",
              "Ferri Ghat",
              "Fulbarigate (Phulbari Gate)",
              "Gagan Babu Road",
              "Gallamari",
              "Gilatala",
              "Goalkhali",
              "Gobarchaka",
              "Gollamari",
              "Gunagati",
              "Hadis Park Area",
              "Haji Mohsin Road",
              "Hasnabad",
              "Housing Estate (Khalishpur)",
              "Iqbal Nagar",
              "Islamampur",
              "Joragate",
              "KDA Avenue",
              "KDA New Market Area",
              "Kashipur",
              "Khalishpur (Gojar Mor)",
              "Khalishpur (New Market)",
              "Khalishpur Ghorkhali",
              "Khalishpur Housing Estate",
              "Khalishpur Notun Rasta",
              "Khan Jahan Ali Road",
              "Khanjahan Ali Thana",
              "Khulna Medical College Area",
              "Khulna University Area",
              "Khulna Zilla School Area",
              "KUET Campus",
              "KUET Road",
              "Labanchora (Lobon Chora)",
              "Lions School Area",
              "Lower Jessore Road",
              "Maheshwarpasha",
              "Maniktala",
              "Mirerdanga",
              "Mistripara",
              "Moilapota (Moylapota)",
              "Mollah Para",
              "Mongla Port Area (Khulna Office)",
              "Moulvi Para",
              "Mujgunni",
              "Mujgunni R/A",
              "Musalman Para",
              "Muzgunni Highway",
              "Navy Colony",
              "Nayabati",
              "Nazrul Nagar",
              "New Market Area",
              "Nirala (R/A)",
              "Nirala Mor",
              "Notun Rasta",
              "Nur Nagar",
              "Pabla",
              "Picture Palace More",
              "Pioneer College Area",
              "Pamper More (Power House)",
              "PTI More",
              "Rayermahal",
              "Rupsha",
              "Rupsha Stand",
              "Rupsha Traffic More",
              "Royal More",
              "Sat Rasta (Seven Roads)",
              "Shantidham More",
              "Shantinagar",
              "Sheikh Para",
              "Sher-e-Bangla Road",
              "Shib Bari More",
              "Shipyard Area",
              "Sonadanga",
              "Sonadanga Bus Stand",
              "Sonadanga R/A (Phase 1)",
              "Sonadanga R/A (Phase 2)",
              "South Central Road",
              "Stadium Area",
              "Tanker Road",
              "Tarer Pukur",
              "Teligati",
              "Tootpara",
              "Tootpara Central Road",
              "Tootpara Hospital Road",
              "Tootpara Main Road",
              "Upper Jessore Road",
              "West Mekot Road",
              "Zero Point",
              "Zia Hall Area",
            ],
          },
          batiaghata: {
            name: "Batiaghata",
            locations: ["Batiaghata", "Dastipur"],
          },
          dacope: { name: "Dacope", locations: ["Dacope", "Dumuria"] },
          phultala: { name: "Phultala", locations: ["Phultala", "Kasipur"] },
          terokhada: {
            name: "Terokhada",
            locations: ["Terokhada", "Paikgachha"],
          },
        },
      },
      bagerhat: {
        name: "Bagerhat",
        thanas: {
          bagerhat_sadar: {
            name: "Bagerhat Sadar",
            locations: ["Bagerhat", "Rajapur"],
          },
          chitalmari: {
            name: "Chitalmari",
            locations: ["Chitalmari", "Nandigram"],
          },
          morrelganj: {
            name: "Morrelganj",
            locations: ["Morrelganj", "Patkelghata"],
          },
          mongla: { name: "Mongla", locations: ["Mongla", "Kora"] },
          kachua: { name: "Kachua", locations: ["Kachua", "Sarankhola"] },
        },
      },
      satkhira: {
        name: "Satkhira",
        thanas: {
          satkhira_sadar: {
            name: "Satkhira Sadar",
            locations: ["Satkhira", "Rajpur"],
          },
          kaliganj: { name: "Kaliganj", locations: ["Kaliganj", "Tala"] },
          ashashuni: { name: "Ashashuni", locations: ["Ashashuni", "Bankra"] },
          shyamnagar: {
            name: "Shyamnagar",
            locations: ["Shyamnagar", "Hashimara"],
          },
          debhata: { name: "Debhata", locations: ["Debhata", "Chandpur"] },
        },
      },
      jessore: {
        name: "Jessore",
        thanas: {
          jessore_sadar: {
            name: "Jessore Sadar",
            locations: ["Jessore", "Gazi Purur Ghat"],
          },
          abhaynagar: {
            name: "Abhaynagar",
            locations: ["Abhaynagar", "Jatpur"],
          },
          manirampur: {
            name: "Manirampur",
            locations: ["Manirampur", "Vromonnagar"],
          },
          chaugachha: {
            name: "Chaugachha",
            locations: ["Chaugachha", "Naldangi"],
          },
        },
      },
      magura: {
        name: "Magura",
        thanas: {
          magura_sadar: {
            name: "Magura Sadar",
            locations: ["Magura", "Krishnanagar"],
          },
          shalikha: {
            name: "Shalikha",
            locations: ["Shalikha", "Purushottampur"],
          },
          sreepur: { name: "Sreepur", locations: ["Sreepur", "Uttarpara"] },
          nagarpur: { name: "Nagarpur", locations: ["Nagarpur", "Satuli"] },
        },
      },
      narail: {
        name: "Narail",
        thanas: {
          narail_sadar: {
            name: "Narail Sadar",
            locations: ["Narail", "Modhukhali"],
          },
          lohagara: { name: "Lohagara", locations: ["Lohagara", "Polashpur"] },
          kalia: { name: "Kalia", locations: ["Kalia", "Banarganj"] },
        },
      },
    },
  },
  rangpur: {
    name: "Rangpur",
    districts: {
      rangpur: {
        name: "Rangpur",
        thanas: {
          rangpur_sadar: {
            name: "Rangpur Sadar",
            locations: [
              "Alamnagar",
              "Ashratpur",
              "Bahar Kachna",
              "Begum Rokeya University Area (BRUR)",
              "Betpotti",
              "Binodpur",
              "Boiragi Para",
              "Burirhat",
              "C.O. Bazar",
              "Cadet College Area",
              "Cantonment Area",
              "Carmichael College Area",
              "Central Road",
              "Charakdanga",
              "Check Post",
              "City Bazar",
              "Civil Surgeon Office Area",
              "Darshana",
              "Dhap",
              "Dhap Engineer Para",
              "Dhap Hazi Para",
              "Dhap Jail Road",
              "Dhap Lalkuthi",
              "Dhap Medical More (Rangpur Medical Area)",
              "Dhap Pasari Para",
              "Dhap Sagarpara",
              "Dharmodas",
              "G.L. Roy Road",
              "Ganeshpur",
              "Guptapara",
              "Gurati Para",
              "Hajirhat (Hazirhat)",
              "Hanumantola",
              "Haragach",
              "Indrarara",
              "Islampur",
              "Jahaj Company More",
              "Jummapara",
              "Kachari Bazar",
              "Kamal Kachna",
              "Kellaband",
              "Keranipara",
              "Khamar More",
              "Kotwali",
              "Lalbagh",
              "Lalbagh Bazar",
              "Mahiganj",
              "Medical Purbogate",
              "Modern More",
              "Mominpur",
              "Mulatol",
              "Munshipara",
              "New Jummapara",
              "New Senpara",
              "Nisbetganj",
              "Nurpur",
              "Paira Chattar (Payra Chattar)",
              "Palpara",
              "Park More",
              "Pashari Para",
              "Police Line",
              "Porshuram",
              "Pouro Bazar",
              "Press Club Area",
              "Radhaballav",
              "Rail Station Area",
              "Rangpur Sadar",
              "RK Road",
              "Robertsonganj",
              "Sahebganj",
              "Salban (Shalbon)",
              "Satmatha",
              "Senpara",
              "Seven Miles",
              "Shapla Chattar",
              "Station Road",
              "Super Market",
              "Tajhat",
              "Terminal Area",
              "Zila School Area",
            ],
          },
          mithapukur: {
            name: "Mithapukur",
            locations: ["Mithapukur", "Kaunia"],
          },
          pirganj: { name: "Pirganj", locations: ["Pirganj", "Gangachara"] },
          kaunia: { name: "Kaunia", locations: ["Kaunia", "Chakhar"] },
          badarganj: { name: "Badarganj", locations: ["Badarganj", "Saidpur"] },
        },
      },
      gaibandha: {
        name: "Gaibandha",
        thanas: {
          gaibandha_sadar: {
            name: "Gaibandha Sadar",
            locations: ["Gaibandha", "Palashbari"],
          },
          sundarban: {
            name: "Sundarban",
            locations: ["Sundarban", "Sadulsaidpur"],
          },
          phulchari: { name: "Phulchari", locations: ["Phulchari", "Porsha"] },
          saddarganj: {
            name: "Saddarganj",
            locations: ["Saddarganj", "Thakurgaon"],
          },
        },
      },
      kurigram: {
        name: "Kurigram",
        thanas: {
          kurigram_sadar: {
            name: "Kurigram Sadar",
            locations: ["Kurigram", "Haluagarh"],
          },
          ulipur: { name: "Ulipur", locations: ["Ulipur", "Rajibpur"] },
          bhurungamari: {
            name: "Bhurungamari",
            locations: ["Bhurungamari", "Rowmari"],
          },
          nageshwari: {
            name: "Nageshwari",
            locations: ["Nageshwari", "Fulbari"],
          },
        },
      },
      dinajpur: {
        name: "Dinajpur",
        thanas: {
          dinajpur_sadar: {
            name: "Dinajpur Sadar",
            locations: ["Dinajpur", "Khhanpur"],
          },
          birganj: {
            name: "Birganj",
            locations: ["Birganj", "Dakshin Dinajpur"],
          },
          ghoraghat: {
            name: "Ghoraghat",
            locations: ["Ghoraghat", "Phulbari"],
          },
          birampur: { name: "Birampur", locations: ["Birampur", "Kaharole"] },
        },
      },
      thakurgaon: {
        name: "Thakurgaon",
        thanas: {
          thakurgaon_sadar: {
            name: "Thakurgaon Sadar",
            locations: ["Thakurgaon", "Ullapur"],
          },
          pirganj: { name: "Pirganj", locations: ["Pirganj", "Gangachara"] },
          ranisankail: {
            name: "Ranisankail",
            locations: ["Ranisankail", "Kabapukur"],
          },
          baliadangi: {
            name: "Baliadangi",
            locations: ["Baliadangi", "Charara"],
          },
        },
      },
      panchagarh: {
        name: "Panchagarh",
        thanas: {
          panchagarh_sadar: {
            name: "Panchagarh Sadar",
            locations: ["Panchagarh", "Mamaria"],
          },
          tetulia: { name: "Tetulia", locations: ["Tetulia", "Boda"] },
          debiganj: { name: "Debiganj", locations: ["Debiganj", "Sundara"] },
          atwari: { name: "Atwari", locations: ["Atwari", "Amliganj"] },
        },
      },
      lalmonirhat: {
        name: "Lalmonirhat",
        thanas: {
          lalmonirhat_sadar: {
            name: "Lalmonirhat Sadar",
            locations: ["Lalmonirhat", "Nilpur"],
          },
          kamalpur: { name: "Kamalpur", locations: ["Kamalpur", "Baluamari"] },
          patgram: { name: "Patgram", locations: ["Patgram", "Hatibandha"] },
          shibganj: { name: "Shibganj", locations: ["Shibganj", "Aditmari"] },
        },
      },
    },
  },
  mymensingh: {
    name: "Mymensingh",
    districts: {
      mymensingh: {
        name: "Mymensingh",
        thanas: {
          mymensingh_sadar: {
            name: "Mymensingh Sadar",
            locations: [
              "Akua (Wireless More)",
              "Akua Chowrangi More",
              "Alalpur",
              "Aminpur",
              "Amodabad",
              "Amritala",
              "Atharobari",
              "Baghmara",
              "Balashpur",
              "Bapm ar Mor",
              "Barera",
              "BAU Campus (Bangladesh Agricultural University)",
              "Bhatara",
              "Bhatikashor",
              "Bipin Park Area",
              "Boira",
              "Boro Bazar",
              "Boundary Road",
              "Bridge More (Shambhuganj Bridge)",
              "By-Pass More",
              "C.K. Ghosh Road",
              "Cantonment Area",
              "Char Kalibari",
              "Charpara (Medical College Area)",
              "China More",
              "Choto Bazar",
              "Churkhai (CBMC Area)",
              "Circuit House Area",
              "College Road (Ananda Mohan College)",
              "Digharkanda",
              "Durgabari",
              "Ganginarpar",
              "Gohailkandi",
              "Golpukur Par",
              "Gouripur",
              "Gulki Bari",
              "Haluaghat",
              "Hospital Road",
              "Jubilee Ghat",
              "Jubli Tank Area",
              "Kachari Ferry Ghat",
              "Kachijhuli",
              "Kalibari",
              "Kankarkanda",
              "Kashiabagan",
              "Kathgola Bazar",
              "Kewatkhali",
              "Khagdahar",
              "Khamar More",
              "Kristopur",
              "Mashkanda (Maskanda)",
              "Maskanda Bus Stand",
              "Medical College Gate",
              "Muktagacha",
              "Mymensingh Sadar",
              "Nahar Road",
              "Nandail",
              "Natun Bazar",
              "Naodahar",
              "Naomahal",
              "Paddapara",
              "Panditpara",
              "Pashchim Akua",
              "Patgudam (Bridge More)",
              "Phulpur",
              "Police Line",
              "Polytechnic Area",
              "Purohitpara",
              "Rahmatpur",
              "Railway Station Area",
              "Rambabu Road",
              "Saheb Ali Road",
              "Sankipara",
              "Sehra",
              "Shambhuganj",
              "Shankipara",
              "Shikarikanda",
              "Shoshi Lodge Area",
              "Station Road",
              "Swadeshi Bazar",
              "Taltola",
              "Thanaghat",
              "Town Hall Area",
              "Trishal (Kabi Nazrul University Area)",
              "Valuka (Bhaluka)",
              "Zero Point",
            ],
          },
          dhobaura: { name: "Dhobaura", locations: ["Dhobaura", "Kasba"] },
          bhaluka: { name: "Bhaluka", locations: ["Bhaluka", "Borogang"] },
          gaffargaon: {
            name: "Gaffargaon",
            locations: ["Gaffargaon", "Ashiana"],
          },
        },
      },
      jamalpur: {
        name: "Jamalpur",
        thanas: {
          jamalpur_sadar: {
            name: "Jamalpur Sadar",
            locations: ["Jamalpur", "Banani Nagar"],
          },
          madarganj: { name: "Madarganj", locations: ["Madarganj", "Dulpur"] },
          islamnagar: {
            name: "Islamnagar",
            locations: ["Islamnagar", "Kapaspara"],
          },
          sarisaram: {
            name: "Sarisaram",
            locations: ["Sarisaram", "Charshail"],
          },
        },
      },
      sherpur: {
        name: "Sherpur",
        thanas: {
          sherpur_sadar: {
            name: "Sherpur Sadar",
            locations: ["Sherpur", "Rongpur"],
          },
          nalitabari: {
            name: "Nalitabari",
            locations: ["Nalitabari", "Bajitpur"],
          },
          nakshal: { name: "Nakshal", locations: ["Nakshal", "Fatehjang"] },
          sreebordi: {
            name: "Sreebordi",
            locations: ["Sreebordi", "Kalmakanda"],
          },
        },
      },
      netrokona: {
        name: "Netrokona",
        thanas: {
          netrokona_sadar: {
            name: "Netrokona Sadar",
            locations: ["Netrokona", "Trishal"],
          },
          durgapur: { name: "Durgapur", locations: ["Durgapur", "Shahbazpur"] },
          atpara: { name: "Atpara", locations: ["Atpara", "Purnapur"] },
          kendua: { name: "Kendua", locations: ["Kendua", "Nilpur"] },
        },
      },
    },
  },
  chattogram: {
    name: "Chattogram",
    districts: {
      chattogram: {
        name: "Chattogram",
        thanas: {
          chattogram_sadar: {
            name: "Chattogram Sadar",
            locations: [
              "Agrabad",
              "Agrabad CDA R/A",
              "AK Khan More",
              "Alankar More",
              "Aman Bazar",
              "Anderkilla",
              "Asadganj",
              "Aturar Depot",
              "Bahaddarhat",
              "Bakalia (East/West)",
              "Baluchara",
              "Bandar (Port Area)",
              "Barik Building",
              "Batali Hill",
              "Bayezid",
              "Bayezid Bostami",
              "Bibir Hat",
              "Boxirhat",
              "Katalganj (Catalgonj)",
              "CDA Avenue",
              "Cement Crossing",
              "Chandanpura",
              "Chandgaon",
              "Chandgaon R/A",
              "Chawkbazar",
              "Chittagong College Area",
              "Chittagong University (CU) Area",
              "Chowmuhani",
              "Colonel Hat",
              "Customs More",
              "Dampara",
              "DC Hill",
              "Dewanhat",
              "Dewan Bazar",
              "Double Mooring",
              "Enayet Bazar",
              "EPZ Area",
              "Firingi Bazar",
              "Foy's Lake",
              "Free Port",
              "GEC Circle",
              "Ghatforhadbag",
              "Gosaildanga",
              "Halishahar",
              "Halishahar (Block A-L)",
              "Hamzarbag",
              "Hathazari Road",
              "Ice Factory Road",
              "Ispahani",
              "Jalalabad",
              "Jamal Khan",
              "Jhautala",
              "Jubilee Road",
              "Kadamtali",
              "Kalamia Bazar",
              "Kapasgola",
              "Karnaphuli EPZ",
              "Katalganj",
              "Kazir Dewri",
              "Khatunganj",
              "Khulshi (North)",
              "Khulshi (South)",
              "Khulshi R/A",
              "Kotwali",
              "Kulgaon",
              "Lalkhan Bazar",
              "Love Lane",
              "Madarbari",
              "Madunaghat",
              "Mehedibagh",
              "Mohara",
              "Momin Road",
              "Muradpur",
              "Nasirabad",
              "Nasirabad Housing Society",
              "Navy Colony",
              "Nayabazar",
              "New Market (Reazuddin Bazar)",
              "New Mooring",
              "OR Nizam Road",
              "Oxygen",
              "Pahartali",
              "Panchlaish",
              "Panchlaish R/A",
              "Patenga",
              "Pathantuli",
              "Pathorghata",
              "Polytechnic Area",
              "Port Colony",
              "Probartak Sangha",
              "Rahattarpul",
              "Rampur",
              "Raufabad",
              "Sadarghat",
              "Salt Gola",
              "Sholashahar",
              "Sholashahar Gate 2",
              "Steel Mill",
              "Strand Road",
              "Sugandha R/A",
              "Surson Road",
              "Teribazar",
              "Tigerpass",
              "Wasa More",
              "Wireless More",
            ],
          },
          halishahar: {
            name: "Halishahar",
            locations: ["Halishahar", "Patenga", "Pahartali"],
          },
          patenga: { name: "Patenga", locations: ["Patenga", "Karnaphuli"] },
          mirsarai: { name: "Mirsarai", locations: ["Mirsarai", "Banshbaria"] },
          sandwip: { name: "Sandwip", locations: ["Sandwip", "North Sandwip"] },
        },
      },
      cox_bazar: {
        name: "Cox's Bazar",
        thanas: {
          cox_bazar_sadar: {
            name: "Cox's Bazar Sadar",
            locations: ["Cox's Bazar", "Kolachahari", "Laboni"],
          },
          teknaf: {
            name: "Teknaf",
            locations: ["Teknaf", "Saint Martin's Island"],
          },
          ukhia: { name: "Ukhia", locations: ["Ukhia", "Makri Para"] },
          ramu: { name: "Ramu", locations: ["Ramu", "Tanipara"] },
          chakaria: { name: "Chakaria", locations: ["Chakaria", "Matarbari"] },
        },
      },
      feni: {
        name: "Feni",
        thanas: {
          feni_sadar: {
            name: "Feni Sadar",
            locations: ["Feni", "Daganbhuiyan"],
          },
          chhagalnaiya: {
            name: "Chhagalnaiya",
            locations: ["Chhagalnaiya", "Sharifpur"],
          },
          parshuram: {
            name: "Parshuram",
            locations: ["Parshuram", "Gazi Nagar"],
          },
          sonagazi: { name: "Sonagazi", locations: ["Sonagazi", "Chatgaon"] },
        },
      },
      noakhali: {
        name: "Noakhali",
        thanas: {
          noakhali_sadar: {
            name: "Noakhali Sadar",
            locations: ["Noakhali", "Lakshmipur Para"],
          },
          begumganj: {
            name: "Begumganj",
            locations: ["Begumganj", "Dakshin Para"],
          },
          chatkhil: { name: "Chatkhil", locations: ["Chatkhil", "Sonpur"] },
          sombhuganj: {
            name: "Sombhuganj",
            locations: ["Sombhuganj", "Rajnagar"],
          },
        },
      },
      lakshmipur: {
        name: "Lakshmipur",
        thanas: {
          lakshmipur_sadar: {
            name: "Lakshmipur Sadar",
            locations: ["Lakshmipur", "Sujanagar"],
          },
          ramganj: { name: "Ramganj", locations: ["Ramganj", "Tekerhat"] },
          kamalnagar: {
            name: "Kamalnagar",
            locations: ["Kamalnagar", "Niamati"],
          },
          raipur: { name: "Raipur", locations: ["Raipur", "Bashmi"] },
        },
      },
      cumilla: {
        name: "Cumilla",
        thanas: {
          cumilla_sadar: {
            name: "Cumilla Sadar",
            locations: ["Cumilla", "Naya Nagar", "Chandpur"],
          },
          chandpur: { name: "Chandpur", locations: ["Chandpur", "Laksam"] },
          laksam: { name: "Laksam", locations: ["Laksam", "Monoharganj"] },
          monoharganj: {
            name: "Monoharganj",
            locations: ["Monoharganj", "Debidwar"],
          },
          debidwar: { name: "Debidwar", locations: ["Debidwar", "Homna"] },
        },
      },
      khagrachari: {
        name: "Khagrachari",
        thanas: {
          khagrachari_sadar: {
            name: "Khagrachari Sadar",
            locations: ["Khagrachari", "Kasalong"],
          },
          dighinala: { name: "Dighinala", locations: ["Dighinala", "Shedmon"] },
          matiranga: {
            name: "Matiranga",
            locations: ["Matiranga", "Bandukbil"],
          },
          rankhine: { name: "Rankhine", locations: ["Rankhine", "Guimara"] },
        },
      },
      rangamati: {
        name: "Rangamati",
        thanas: {
          rangamati_sadar: {
            name: "Rangamati Sadar",
            locations: ["Rangamati", "Kaptai Lake"],
          },
          kaptai: { name: "Kaptai", locations: ["Kaptai", "Samarbil"] },
          kawkhali: { name: "Kawkhali", locations: ["Kawkhali", "Bonokhali"] },
          baghaichhari: {
            name: "Baghaichhari",
            locations: ["Baghaichhari", "Jatindra"],
          },
        },
      },
      bandarban: {
        name: "Bandarban",
        thanas: {
          bandarban_sadar: {
            name: "Bandarban Sadar",
            locations: ["Bandarban", "Ghumdhum"],
          },
          thanchi: { name: "Thanchi", locations: ["Thanchi", "Balaghata"] },
          rowangchari: {
            name: "Rowangchari",
            locations: ["Rowangchari", "Digarchari"],
          },
          lama: { name: "Lama", locations: ["Lama", "Naikhongchari"] },
        },
      },
    },
  },
  sylhet: {
    name: "Sylhet",
    districts: {
      sylhet: {
        name: "Sylhet",
        thanas: {
          sylhet_sadar: {
            name: "Sylhet Sadar",
            locations: [
              "Airport Road",
              "Akhalia",
              "Akhalia Ghat",
              "Akhalia Surma R/A",
              "Al-Hamra",
              "Ambarkhana",
              "Bagbari",
              "Baluchar",
              "Bandar Bazar",
              "Barutkhana",
              "Beanibazar",
              "Bilpar",
              "Bishwa Road",
              "Bondor",
              "Borshola",
              "Chalibandar",
              "Chawkbazar",
              "Chowhatta",
              "Chowkidekhi",
              "Dargah Gate (Dargah Mahalla)",
              "Dargah Road",
              "Darshan Deuri",
              "Dhopadighir Par",
              "Eidgah (Shahi Eidgah)",
              "Electric Supply",
              "Fazilchisht",
              "Fenchuganj",
              "Gaighat",
              "Golapganj",
              "Goyabari",
              "Hawapara",
              "Housing Estate",
              "Islamia College Area",
              "Jalalabad",
              "Jalalabad R/A",
              "Jallarpar",
              "Jhalo Para",
              "Jitumoia Point",
              "Kadamtoli",
              "Kajalshah",
              "Kalighat",
              "Kanishail",
              "Kazir Bazar",
              "Kazitula",
              "Khasdobir",
              "Khashruzzaman Choudhury Road",
              "Kin Bridge Area (Keane Bridge)",
              "Kumarpara",
              "Lakkatura",
              "Lama Bazar",
              "Lawai",
              "Londoni Road",
              "Madina Market",
              "Malnichara",
              "Mazortila",
              "MC College Area",
              "Mehendibagh (Mendibagh)",
              "Mirabazar",
              "Modhu Shahid",
              "Modhuban",
              "Mojumdari",
              "Mollapara",
              "Munsipara",
              "Naiyorpul",
              "Nayasarak",
              "Osmani Medical College Area",
              "Pathantula",
              "Pir Moholla",
              "Police Line",
              "Ponitula",
              "Rajar Goli",
              "Raynagar",
              "Rikabi Bazar",
              "Rose View Area",
              "Sagardighir Par",
              "Shahjalal Uposhahar (Sector A-E)",
              "Shahjalal Uposhahar (Main Road)",
              "Shahparan",
              "Shahi Eidgah",
              "Shapla Bagh",
              "Sheikhghat",
              "Shibgonj",
              "Sobhanighat",
              "Sonatola",
              "South Surma",
              "Subid Bazar",
              "Sunampur",
              "SUST Campus (Shahjalal University)",
              "SUST Gate",
              "Sylhet Sadar",
              "Taltola",
              "Technical Road",
              "Teroratan",
              "Tilagor",
              "Topoban R/A",
              "Upashahar",
              "Zindabazar",
            ],
          },
          balighaat: {
            name: "Balighaat",
            locations: ["Balighaat", "Moglabazar"],
          },
          zindabazar: {
            name: "Zindabazar",
            locations: ["Zindabazar", "Osmani Nagar"],
          },
          amberkhana: {
            name: "Amberkhana",
            locations: ["Amberkhana", "Keraniganj"],
          },
        },
      },
      moulvibazar: {
        name: "Moulvibazar",
        thanas: {
          moulvibazar_sadar: {
            name: "Moulvibazar Sadar",
            locations: ["Moulvibazar", "Kamalganj"],
          },
          barlekha: { name: "Barlekha", locations: ["Barlekha", "Kulaura"] },
          juri: { name: "Juri", locations: ["Juri", "Srimangal"] },
          kulaura: { name: "Kulaura", locations: ["Kulaura", "Banarip"] },
        },
      },
      sunamganj: {
        name: "Sunamganj",
        thanas: {
          sunamganj_sadar: {
            name: "Sunamganj Sadar",
            locations: ["Sunamganj", "Bishwamvarpur"],
          },
          bishwamvarpur: {
            name: "Bishwamvarpur",
            locations: ["Bishwamvarpur", "Dowarabazar"],
          },
          dowarabazar: {
            name: "Dowarabazar",
            locations: ["Dowarabazar", "Jagannathpur"],
          },
          jagannathpur: {
            name: "Jagannathpur",
            locations: ["Jagannathpur", "Taherpur"],
          },
        },
      },
      habiganj: {
        name: "Habiganj",
        thanas: {
          habiganj_sadar: {
            name: "Habiganj Sadar",
            locations: ["Habiganj", "Lakhai"],
          },
          baniachang: {
            name: "Baniachang",
            locations: ["Baniachang", "Madhya Gram"],
          },
          bahubal: { name: "Bahubal", locations: ["Bahubal", "Chandpur"] },
          lakhai: { name: "Lakhai", locations: ["Lakhai", "Nilbari"] },
        },
      },
    },
  },
  barishal: {
    name: "Barishal",
    districts: {
      barishal: {
        name: "Barishal",
        thanas: {
          barishal_sadar: {
            name: "Barishal Sadar",
            locations: [
              "Agarpur",
              "Alekanda",
              "Amanatganj",
              "Amtala",
              "Amtala More",
              "Arpangashia",
              "Askar Kalibari",
              "Bagura Road (Bogura Road)",
              "Band Road",
              "Banglabazar",
              "Bank Para",
              "Baptist Mission Road",
              "Barishal Cadet College Area",
              "Barishal Sadar",
              "Barishal University Area (BU)",
              "Bazar Road",
              "Bell's Park (Bangabandhu Udyan)",
              "Bhatara",
              "BM College Area (Brojomohun College)",
              "BM College Road",
              "Bottola",
              "Brown Compound",
              "BSCIC Industrial Area",
              "Bund Road",
              "C&B Road",
              "Chalk Bazar",
              "Chandmari",
              "Charbaria",
              "Chawkbazar",
              "Choumatha",
              "Chowmatha",
              "Christian Para",
              "Circuit House Area",
              "College Row",
              "Count Road",
              "Daptarkhana",
              "DC Ghat",
              "Dighirpar",
              "Fakir Bari Road",
              "Fazlul Huq Avenue",
              "Gagonoli",
              "Gazipur",
              "Girja Moholla",
              "Gorostan Road",
              "Gournadi",
              "Hatem Ali College Area",
              "Hatkhola",
              "Hemayet Uddin Road",
              "Hospital Road",
              "Housing Estate",
              "Ichakati",
              "Jail Gate",
              "Janota Bank More",
              "Jordan Road",
              "Jor Mosque",
              "Kalibari Road",
              "Kalijira",
              "Kashipur",
              "Kashipur Bazar",
              "Katpotti",
              "Kawnia",
              "Kawnia Main Road",
              "Kawnia Branch Road",
              "Kazipara",
              "Kellapara",
              "Koro Tola",
              "Launch Ghat",
              "Mallick Road",
              "Medical College Area (SBMC)",
              "Medical College Lane",
              "Metharkanda",
              "Munshir Garage",
              "Nabagram Road (Nobogram)",
              "Nathullabad (Central Bus Terminal)",
              "Natun Bazar",
              "Nazir Moholla",
              "Nazirpool",
              "New Circular Road",
              "Notun Bazar",
              "Oxford Mission Road",
              "Palashpur",
              "Parara Road",
              "Police Line",
              "Polytechnic Road",
              "Port Road",
              "Rasulpur",
              "Rupatoli",
              "Rupatoli Housing",
              "Sadar Road",
              "Sagardi",
              "Sher-e-Bangla Road",
              "Shitalakhola",
              "Sreenath Chatterjee Lane",
              "Stadium Area",
              "Steamer Ghat",
              "Taragonia",
              "Thana Council",
              "Tiakhali",
              "Uzirpur",
              "Zia Sarak",
              "Zila School Area",
            ],
          },
          amlakandi: {
            name: "Amlakandi",
            locations: ["Amlakandi", "Aagaraun"],
          },
          hizla: { name: "Hizla", locations: ["Hizla", "Gaunadi"] },
          bakerganj: { name: "Bakerganj", locations: ["Bakerganj", "Barisal"] },
        },
      },
      pirojpur: {
        name: "Pirojpur",
        thanas: {
          pirojpur_sadar: {
            name: "Pirojpur Sadar",
            locations: ["Pirojpur", "Nazirpur"],
          },
          nazirpur: { name: "Nazirpur", locations: ["Nazirpur", "Sawrabari"] },
          kawkhali: { name: "Kawkhali", locations: ["Kawkhali", "Bhandaria"] },
          bhandaria: {
            name: "Bhandaria",
            locations: ["Bhandaria", "Indurkani"],
          },
        },
      },
      jhalokati: {
        name: "Jhalokati",
        thanas: {
          jhalokati_sadar: {
            name: "Jhalokati Sadar",
            locations: ["Jhalokati", "Rajaiganj"],
          },
          rajaiganj: {
            name: "Rajaiganj",
            locations: ["Rajaiganj", "Nalchity"],
          },
          nalchity: { name: "Nalchity", locations: ["Nalchity", "Jhalokati"] },
        },
      },
      patuakhali: {
        name: "Patuakhali",
        thanas: {
          patuakhali_sadar: {
            name: "Patuakhali Sadar",
            locations: ["Patuakhali", "Dumki", "Kalapara"],
          },
          dumki: { name: "Dumki", locations: ["Dumki", "Rangabali"] },
          kalapara: { name: "Kalapara", locations: ["Kalapara", "Nangalkot"] },
          rangabali: { name: "Rangabali", locations: ["Rangabali", "Tejgaon"] },
        },
      },
      bhola: {
        name: "Bhola",
        thanas: {
          bhola_sadar: {
            name: "Bhola Sadar",
            locations: ["Bhola", "Manpura", "Daulkandi"],
          },
          borhanuddin: {
            name: "Borhanuddin",
            locations: ["Borhanuddin", "Kachua"],
          },
          daulkandi: {
            name: "Daulkandi",
            locations: ["Daulkandi", "Tajumuddin"],
          },
          manpura: { name: "Manpura", locations: ["Manpura", "Char Fashion"] },
        },
      },
      borguna: {
        name: "Borguna",
        thanas: {
          borguna_sadar: {
            name: "Borguna Sadar",
            locations: ["Borguna", "Amtali", "Patharghata"],
          },
          amtali: { name: "Amtali", locations: ["Amtali", "Jalikhali"] },
          patharghata: {
            name: "Patharghata",
            locations: ["Patharghata", "Taltali"],
          },
          taltali: { name: "Taltali", locations: ["Taltali", "Char Changa"] },
        },
      },
    },
  },
};